# https://golangci-lint.run/usage/configuration/
linters:
  disable-all: false  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
  presets:  # 通过preset来快速启用一组相关linter
  fast: false
linters-settings:  # 针对特定linter的配置
  option: value
issues:
  option: value
output:
  option: value
run:  # run options的配置
  option: value
severity:
  option: value